import { TestBed } from '@angular/core/testing';

import { DashboardService } from './dashboard.service';
import { HttpClientModule } from '@angular/common/http';
import { LoginService } from '../../login/services/login.service';

import { of, from } from 'rxjs';
import { Albums } from '../models/search.model';

let httpClientSpy: { get: jasmine.Spy };
let dashboardService: DashboardService;

describe('DashboardService', () => {
  let service: DashboardService;
  let loginService: LoginService;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientModule],
      providers: [LoginService, DashboardService],
    });
    service = TestBed.inject(DashboardService);
  });

  it('Testa a instancia de DashboardService', () => {
    expect(service).toBeTruthy();
  });

  beforeEach(() => {
    loginService = TestBed.inject(LoginService);
    httpClientSpy = jasmine.createSpyObj('HttpClient', [
      'get',
      'post',
      'put',
      'delete',
    ]);
    dashboardService = new DashboardService(httpClientSpy as any, loginService);
  });

  it('Testa GET de albums da api do spotify', () => {
    const album: Albums = {
      href: '',
      items: [
        {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/1TYJOhNSxMOODWiDVhuyZb',
              },
              href: 'https://api.spotify.com/v1/artists/1TYJOhNSxMOODWiDVhuyZb',
              id: '1TYJOhNSxMOODWiDVhuyZb',
              name: 'Kawe',
              type: 'artist',
              uri: 'spotify:artist:1TYJOhNSxMOODWiDVhuyZb',
            },
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/4oxFgud0qa3A1tE6JFpFVp',
              },
              href: 'https://api.spotify.com/v1/artists/4oxFgud0qa3A1tE6JFpFVp',
              id: '4oxFgud0qa3A1tE6JFpFVp',
              name: 'JayA Luuck',
              type: 'artist',
              uri: 'spotify:artist:4oxFgud0qa3A1tE6JFpFVp',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/6zhfMgOecZi8lRQ43CO3jL',
          },
          href: 'https://api.spotify.com/v1/albums/6zhfMgOecZi8lRQ43CO3jL',
          id: '6zhfMgOecZi8lRQ43CO3jL',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/1763b7fa866d83634b55207d888b811a8ca57cf8',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/f6e99924592b358c0a76e3d902cd7577b5b4fde1',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/aa64954cfdc6d51fac7fb00ac80a715e30a5e578',
              width: 64,
            },
          ],
          name: 'Jordan',
          release_date: '2019-12-13',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:6zhfMgOecZi8lRQ43CO3jL',
        },
        {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/7ALIMskSScecdJr78qvB9V',
              },
              href: 'https://api.spotify.com/v1/artists/7ALIMskSScecdJr78qvB9V',
              id: '7ALIMskSScecdJr78qvB9V',
              name: 'Leozin',
              type: 'artist',
              uri: 'spotify:artist:7ALIMskSScecdJr78qvB9V',
            },
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/5Ynf8bbQV9ICbK3vZoPxGF',
              },
              href: 'https://api.spotify.com/v1/artists/5Ynf8bbQV9ICbK3vZoPxGF',
              id: '5Ynf8bbQV9ICbK3vZoPxGF',
              name: 'Dudu',
              type: 'artist',
              uri: 'spotify:artist:5Ynf8bbQV9ICbK3vZoPxGF',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/4LZLO3z85SVBMqKp2tOIxr',
          },
          href: 'https://api.spotify.com/v1/albums/4LZLO3z85SVBMqKp2tOIxr',
          id: '4LZLO3z85SVBMqKp2tOIxr',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b273e53f4a179446f6934f7a1445',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e02e53f4a179446f6934f7a1445',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d00004851e53f4a179446f6934f7a1445',
              width: 64,
            },
          ],
          name: "Jordan Boy'z",
          release_date: '2019-06-06',
          release_date_precision: 'day',
          total_tracks: 5,
          type: 'album',
          uri: 'spotify:album:4LZLO3z85SVBMqKp2tOIxr',
        },
        {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/60wslYioiBcxSTInM4nIy2',
              },
              href: 'https://api.spotify.com/v1/artists/60wslYioiBcxSTInM4nIy2',
              id: '60wslYioiBcxSTInM4nIy2',
              name: 'Jordan Fisher',
              type: 'artist',
              uri: 'spotify:artist:60wslYioiBcxSTInM4nIy2',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/6zc8a8V90y4SOtcZT6mbOx',
          },
          href: 'https://api.spotify.com/v1/albums/6zc8a8V90y4SOtcZT6mbOx',
          id: '6zc8a8V90y4SOtcZT6mbOx',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b27305a25ed77d913b33ad71d059',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e0205a25ed77d913b33ad71d059',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d0000485105a25ed77d913b33ad71d059',
              width: 64,
            },
          ],
          name: 'Jordan Fisher',
          release_date: '2016-08-19',
          release_date_precision: 'day',
          total_tracks: 4,
          type: 'album',
          uri: 'spotify:album:6zc8a8V90y4SOtcZT6mbOx',
        },
        {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/2qHe4hsn9sRe5qm4uUVXwF',
              },
              href: 'https://api.spotify.com/v1/artists/2qHe4hsn9sRe5qm4uUVXwF',
              id: '2qHe4hsn9sRe5qm4uUVXwF',
              name: 'Jordan Beggs',
              type: 'artist',
              uri: 'spotify:artist:2qHe4hsn9sRe5qm4uUVXwF',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/0lhVRQb6dOfoet7rJtPBYg',
          },
          href: 'https://api.spotify.com/v1/albums/0lhVRQb6dOfoet7rJtPBYg',
          id: '0lhVRQb6dOfoet7rJtPBYg',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b273ed082072637aee4a90d2fdff',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e02ed082072637aee4a90d2fdff',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d00004851ed082072637aee4a90d2fdff',
              width: 64,
            },
          ],
          name: 'She’ll be right',
          release_date: '2019-10-18',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:0lhVRQb6dOfoet7rJtPBYg',
        },
        {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/4NhmH4PFEHpmuRCYsqCvst',
              },
              href: 'https://api.spotify.com/v1/artists/4NhmH4PFEHpmuRCYsqCvst',
              id: '4NhmH4PFEHpmuRCYsqCvst',
              name: 'Jordan Barns',
              type: 'artist',
              uri: 'spotify:artist:4NhmH4PFEHpmuRCYsqCvst',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/1cLj9aIkZRAf2Zb1iqtVz0',
          },
          href: 'https://api.spotify.com/v1/albums/1cLj9aIkZRAf2Zb1iqtVz0',
          id: '1cLj9aIkZRAf2Zb1iqtVz0',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b273415cf23ebd7ae6696e24e4af',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e02415cf23ebd7ae6696e24e4af',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d00004851415cf23ebd7ae6696e24e4af',
              width: 64,
            },
          ],
          name: 'Forrest Gump - Main Title (Feather Theme)',
          release_date: '2019-04-06',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:1cLj9aIkZRAf2Zb1iqtVz0',
        },
        {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/2TbYpxb2aX80gBl9GyvlUq',
              },
              href: 'https://api.spotify.com/v1/artists/2TbYpxb2aX80gBl9GyvlUq',
              id: '2TbYpxb2aX80gBl9GyvlUq',
              name: 'Jordan Teixeira',
              type: 'artist',
              uri: 'spotify:artist:2TbYpxb2aX80gBl9GyvlUq',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/5mjJOaRbrtKFJcDki9IE7i',
          },
          href: 'https://api.spotify.com/v1/albums/5mjJOaRbrtKFJcDki9IE7i',
          id: '5mjJOaRbrtKFJcDki9IE7i',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b2737db6df3dbdfe29488ca74b3d',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e027db6df3dbdfe29488ca74b3d',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d000048517db6df3dbdfe29488ca74b3d',
              width: 64,
            },
          ],
          name: 'Pedra Preciosa (Ao Vivo)',
          release_date: '2017-11-02',
          release_date_precision: 'day',
          total_tracks: 11,
          type: 'album',
          uri: 'spotify:album:5mjJOaRbrtKFJcDki9IE7i',
        },
        {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/0jzpxK7Ni27yIXPpDwl058',
              },
              href: 'https://api.spotify.com/v1/artists/0jzpxK7Ni27yIXPpDwl058',
              id: '0jzpxK7Ni27yIXPpDwl058',
              name: 'DJGWD4',
              type: 'artist',
              uri: 'spotify:artist:0jzpxK7Ni27yIXPpDwl058',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/3fU6q4ofR6otVXLK9K6ja1',
          },
          href: 'https://api.spotify.com/v1/albums/3fU6q4ofR6otVXLK9K6ja1',
          id: '3fU6q4ofR6otVXLK9K6ja1',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b273e7749eaaaf65d8dd39313306',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e02e7749eaaaf65d8dd39313306',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d00004851e7749eaaaf65d8dd39313306',
              width: 64,
            },
          ],
          name: 'Jordan Belfurt',
          release_date: '2020-02-16',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:3fU6q4ofR6otVXLK9K6ja1',
        },
        {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/31qbEjNjXDEezxGBPGtqpN',
              },
              href: 'https://api.spotify.com/v1/artists/31qbEjNjXDEezxGBPGtqpN',
              id: '31qbEjNjXDEezxGBPGtqpN',
              name: 'Jordan Moths',
              type: 'artist',
              uri: 'spotify:artist:31qbEjNjXDEezxGBPGtqpN',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/3iznVmFWlHHXbPiwep3PbI',
          },
          href: 'https://api.spotify.com/v1/albums/3iznVmFWlHHXbPiwep3PbI',
          id: '3iznVmFWlHHXbPiwep3PbI',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/b08a534b552758f7255835260de91f9e1d843853',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/b9474e7cf80bd1efb2e9392f7b96ffe4b3f2bb80',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/9ef6e40a809c5e5ea8d471c7829f9ad10f2bbc50',
              width: 64,
            },
          ],
          name: 'Golden Slumbers',
          release_date: '2017-05-11',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:3iznVmFWlHHXbPiwep3PbI',
        },
        {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/5sE9NBRSflcXdYuzNKRO4J',
              },
              href: 'https://api.spotify.com/v1/artists/5sE9NBRSflcXdYuzNKRO4J',
              id: '5sE9NBRSflcXdYuzNKRO4J',
              name: 'Jordan Maxwell',
              type: 'artist',
              uri: 'spotify:artist:5sE9NBRSflcXdYuzNKRO4J',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/1sfS40ZWSFz2Gy3QyLD0vL',
          },
          href: 'https://api.spotify.com/v1/albums/1sfS40ZWSFz2Gy3QyLD0vL',
          id: '1sfS40ZWSFz2Gy3QyLD0vL',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b2731b6e7f355ac6901ffb5c6070',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e021b6e7f355ac6901ffb5c6070',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d000048511b6e7f355ac6901ffb5c6070',
              width: 64,
            },
          ],
          name: 'Is It Too Much to Ask For - EP',
          release_date: '2017-05-11',
          release_date_precision: 'day',
          total_tracks: 4,
          type: 'album',
          uri: 'spotify:album:1sfS40ZWSFz2Gy3QyLD0vL',
        },
        {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/6TV0LZ3BaEun0OQEh96elP',
              },
              href: 'https://api.spotify.com/v1/artists/6TV0LZ3BaEun0OQEh96elP',
              id: '6TV0LZ3BaEun0OQEh96elP',
              name: 'Jordan Smith',
              type: 'artist',
              uri: 'spotify:artist:6TV0LZ3BaEun0OQEh96elP',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/144abioSp1P3RFW1HujUsX',
          },
          href: 'https://api.spotify.com/v1/albums/144abioSp1P3RFW1HujUsX',
          id: '144abioSp1P3RFW1HujUsX',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b2733d9a8c19e38f38383e37323a',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e023d9a8c19e38f38383e37323a',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d000048513d9a8c19e38f38383e37323a',
              width: 64,
            },
          ],
          name: 'The Complete Season 9 Collection (The Voice Performance)',
          release_date: '2015-12-16',
          release_date_precision: 'day',
          total_tracks: 11,
          type: 'album',
          uri: 'spotify:album:144abioSp1P3RFW1HujUsX',
        },
        {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/3MmklYESte8IJHUjXEqypw',
              },
              href: 'https://api.spotify.com/v1/artists/3MmklYESte8IJHUjXEqypw',
              id: '3MmklYESte8IJHUjXEqypw',
              name: 'Jordane Tumarinson',
              type: 'artist',
              uri: 'spotify:artist:3MmklYESte8IJHUjXEqypw',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/6KjNkS21n7ICAQRmUVrCK7',
          },
          href: 'https://api.spotify.com/v1/albums/6KjNkS21n7ICAQRmUVrCK7',
          id: '6KjNkS21n7ICAQRmUVrCK7',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/88c0b9d67e3512153a68de12fbfd042df046bdf6',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/1a2787c9b7b7f272c0b0718f2ea75b266ce798c0',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ec3cb8296388e7129867f636f6fba07b36b8de0d',
              width: 64,
            },
          ],
          name: 'Automne',
          release_date: '2019-11-29',
          release_date_precision: 'day',
          total_tracks: 2,
          type: 'album',
          uri: 'spotify:album:6KjNkS21n7ICAQRmUVrCK7',
        },
        {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/0TgNiaeQaWssaH9aWjbqnA',
              },
              href: 'https://api.spotify.com/v1/artists/0TgNiaeQaWssaH9aWjbqnA',
              id: '0TgNiaeQaWssaH9aWjbqnA',
              name: 'Jordan Feliz',
              type: 'artist',
              uri: 'spotify:artist:0TgNiaeQaWssaH9aWjbqnA',
            },
          ],
          available_markets: [
            'AD',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'EC',
            'EE',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JP',
            'LI',
            'LT',
            'LU',
            'LV',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'RO',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/65uVVXYJnTGcJZ0rkjtyjX',
          },
          href: 'https://api.spotify.com/v1/albums/65uVVXYJnTGcJZ0rkjtyjX',
          id: '65uVVXYJnTGcJZ0rkjtyjX',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b273c2c206cbe35ae3fd608c8398',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e02c2c206cbe35ae3fd608c8398',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d00004851c2c206cbe35ae3fd608c8398',
              width: 64,
            },
          ],
          name: 'Future',
          release_date: '2018-03-23',
          release_date_precision: 'day',
          total_tracks: 13,
          type: 'album',
          uri: 'spotify:album:65uVVXYJnTGcJZ0rkjtyjX',
        },
        {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/14Y3trk7LaslSFTk1G35rx',
              },
              href: 'https://api.spotify.com/v1/artists/14Y3trk7LaslSFTk1G35rx',
              id: '14Y3trk7LaslSFTk1G35rx',
              name: 'Jordan Clarke',
              type: 'artist',
              uri: 'spotify:artist:14Y3trk7LaslSFTk1G35rx',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/2Gh3whz13f6o7B3ychEmBP',
          },
          href: 'https://api.spotify.com/v1/albums/2Gh3whz13f6o7B3ychEmBP',
          id: '2Gh3whz13f6o7B3ychEmBP',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b2734287869e1015b4bd29c8e800',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e024287869e1015b4bd29c8e800',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d000048514287869e1015b4bd29c8e800',
              width: 64,
            },
          ],
          name: 'Freaks',
          release_date: '2019-02-25',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:2Gh3whz13f6o7B3ychEmBP',
        },
        {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/6TV0LZ3BaEun0OQEh96elP',
              },
              href: 'https://api.spotify.com/v1/artists/6TV0LZ3BaEun0OQEh96elP',
              id: '6TV0LZ3BaEun0OQEh96elP',
              name: 'Jordan Smith',
              type: 'artist',
              uri: 'spotify:artist:6TV0LZ3BaEun0OQEh96elP',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/0khL20OGL3WLDoUbicoKaZ',
          },
          href: 'https://api.spotify.com/v1/albums/0khL20OGL3WLDoUbicoKaZ',
          id: '0khL20OGL3WLDoUbicoKaZ',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b273228615187078ba56af4e665e',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e02228615187078ba56af4e665e',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d00004851228615187078ba56af4e665e',
              width: 64,
            },
          ],
          name: 'Only Love',
          release_date: '2018-08-10',
          release_date_precision: 'day',
          total_tracks: 12,
          type: 'album',
          uri: 'spotify:album:0khL20OGL3WLDoUbicoKaZ',
        },
        {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/0HjYETXAvcL6mzaKjAmH2K',
              },
              href: 'https://api.spotify.com/v1/artists/0HjYETXAvcL6mzaKjAmH2K',
              id: '0HjYETXAvcL6mzaKjAmH2K',
              name: 'Wes Walker',
              type: 'artist',
              uri: 'spotify:artist:0HjYETXAvcL6mzaKjAmH2K',
            },
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/1dfpwerOGBId6qD7LVwpoB',
              },
              href: 'https://api.spotify.com/v1/artists/1dfpwerOGBId6qD7LVwpoB',
              id: '1dfpwerOGBId6qD7LVwpoB',
              name: 'Dyl',
              type: 'artist',
              uri: 'spotify:artist:1dfpwerOGBId6qD7LVwpoB',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/4G2vHAnHSkuzj1VVBJrRbF',
          },
          href: 'https://api.spotify.com/v1/albums/4G2vHAnHSkuzj1VVBJrRbF',
          id: '4G2vHAnHSkuzj1VVBJrRbF',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b27316d9cd79b60c6062036bfadc',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e0216d9cd79b60c6062036bfadc',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d0000485116d9cd79b60c6062036bfadc',
              width: 64,
            },
          ],
          name: 'Jordan Belfort',
          release_date: '2015-08-26',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:4G2vHAnHSkuzj1VVBJrRbF',
        },
        {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/0TgNiaeQaWssaH9aWjbqnA',
              },
              href: 'https://api.spotify.com/v1/artists/0TgNiaeQaWssaH9aWjbqnA',
              id: '0TgNiaeQaWssaH9aWjbqnA',
              name: 'Jordan Feliz',
              type: 'artist',
              uri: 'spotify:artist:0TgNiaeQaWssaH9aWjbqnA',
            },
          ],
          available_markets: [
            'AD',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'EC',
            'EE',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JP',
            'LI',
            'LT',
            'LU',
            'LV',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'RO',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/37b7Y7ow9J8eHcRyEtqaWY',
          },
          href: 'https://api.spotify.com/v1/albums/37b7Y7ow9J8eHcRyEtqaWY',
          id: '37b7Y7ow9J8eHcRyEtqaWY',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b2735c0cc5d4711a5556918a5b1e',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e025c0cc5d4711a5556918a5b1e',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d000048515c0cc5d4711a5556918a5b1e',
              width: 64,
            },
          ],
          name: 'Beloved',
          release_date: '2015-10-02',
          release_date_precision: 'day',
          total_tracks: 10,
          type: 'album',
          uri: 'spotify:album:37b7Y7ow9J8eHcRyEtqaWY',
        },
        {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/24icoQNJSEWNu3XvqKBR68',
              },
              href: 'https://api.spotify.com/v1/artists/24icoQNJSEWNu3XvqKBR68',
              id: '24icoQNJSEWNu3XvqKBR68',
              name: 'Jordan Rakei',
              type: 'artist',
              uri: 'spotify:artist:24icoQNJSEWNu3XvqKBR68',
            },
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/1uiEZYehlNivdK3iQyAbye',
              },
              href: 'https://api.spotify.com/v1/artists/1uiEZYehlNivdK3iQyAbye',
              id: '1uiEZYehlNivdK3iQyAbye',
              name: 'Tom Misch',
              type: 'artist',
              uri: 'spotify:artist:1uiEZYehlNivdK3iQyAbye',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/3ssz8pi55szsiCBRpJr4xV',
          },
          href: 'https://api.spotify.com/v1/albums/3ssz8pi55szsiCBRpJr4xV',
          id: '3ssz8pi55szsiCBRpJr4xV',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b27371c7f35976f88a18009611db',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e0271c7f35976f88a18009611db',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d0000485171c7f35976f88a18009611db',
              width: 64,
            },
          ],
          name: 'Midnight Mischief (Tom Misch Remix)',
          release_date: '2016-09-19',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:3ssz8pi55szsiCBRpJr4xV',
        },
        {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/24WPEGLYPvEsmk4GSDFyST',
              },
              href: 'https://api.spotify.com/v1/artists/24WPEGLYPvEsmk4GSDFyST',
              id: '24WPEGLYPvEsmk4GSDFyST',
              name: 'Jordan Mackampa',
              type: 'artist',
              uri: 'spotify:artist:24WPEGLYPvEsmk4GSDFyST',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/6Z9hbxCbOQlOFdaAU2JvO8',
          },
          href: 'https://api.spotify.com/v1/albums/6Z9hbxCbOQlOFdaAU2JvO8',
          id: '6Z9hbxCbOQlOFdaAU2JvO8',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b273b2cd39df8fca2f0d74f4fb34',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e02b2cd39df8fca2f0d74f4fb34',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d00004851b2cd39df8fca2f0d74f4fb34',
              width: 64,
            },
          ],
          name: 'Physics EP',
          release_date: '2016-09-30',
          release_date_precision: 'day',
          total_tracks: 4,
          type: 'album',
          uri: 'spotify:album:6Z9hbxCbOQlOFdaAU2JvO8',
        },
        {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/31qbEjNjXDEezxGBPGtqpN',
              },
              href: 'https://api.spotify.com/v1/artists/31qbEjNjXDEezxGBPGtqpN',
              id: '31qbEjNjXDEezxGBPGtqpN',
              name: 'Jordan Moths',
              type: 'artist',
              uri: 'spotify:artist:31qbEjNjXDEezxGBPGtqpN',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/1t2baejxuUgbE65JkHrTCn',
          },
          href: 'https://api.spotify.com/v1/albums/1t2baejxuUgbE65JkHrTCn',
          id: '1t2baejxuUgbE65JkHrTCn',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b273364b8ee6090bf3d1a4403290',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e02364b8ee6090bf3d1a4403290',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d00004851364b8ee6090bf3d1a4403290',
              width: 64,
            },
          ],
          name: 'Baa Baa Little Lamb',
          release_date: '2017-05-11',
          release_date_precision: 'day',
          total_tracks: 2,
          type: 'album',
          uri: 'spotify:album:1t2baejxuUgbE65JkHrTCn',
        },
        {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/7mJOpa0R9YYi7vTqMCBeJb',
              },
              href: 'https://api.spotify.com/v1/artists/7mJOpa0R9YYi7vTqMCBeJb',
              id: '7mJOpa0R9YYi7vTqMCBeJb',
              name: 'Jordan Max',
              type: 'artist',
              uri: 'spotify:artist:7mJOpa0R9YYi7vTqMCBeJb',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/7xrJVu4GB4Q6xmhMBqerEZ',
          },
          href: 'https://api.spotify.com/v1/albums/7xrJVu4GB4Q6xmhMBqerEZ',
          id: '7xrJVu4GB4Q6xmhMBqerEZ',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b27377e5b0a8131c3eaf65fef81b',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e0277e5b0a8131c3eaf65fef81b',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d0000485177e5b0a8131c3eaf65fef81b',
              width: 64,
            },
          ],
          name: 'Only One Is King',
          release_date: '2016-03-25',
          release_date_precision: 'day',
          total_tracks: 4,
          type: 'album',
          uri: 'spotify:album:7xrJVu4GB4Q6xmhMBqerEZ',
        },
      ],
      limit: 20,
      next:
        'https://api.spotify.com/v1/search?query=jordan&type=album&offset=20&limit=20',
      offset: 0,
      previous: null,
      total: 10020,
    };

    httpClientSpy.get.and.returnValue(of(album));

    dashboardService.buscaAlbumSpotify('jordan', 0, 20);

    expect(httpClientSpy.get.calls.count()).toBe(1, 'Chama apenas uma vez');
  });
});
